version: '3.8'
services:
  vault:
    image: vault
    restart: unless-stopped
    ports:
      - "8300:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myadmin # Hesham root token
    volumes:
      - ./vault/data:/vault/data
      - ./vault/config:/vault/config

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234 # MySQL root password
      - MYSQL_DATABASE=wp_dp #  WordPress database name
      - MYSQL_USER=wp_user #  WordPress database user
      - MYSQL_PASSWORD=1234 #  database password
    volumes:
      - ./mysql/data:/var/lib/mysql

  wordpress:
    depends_on:
      - mysql
    image: wordpress
    restart: unless-stopped
    ports:
      - "8088:80"
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=wp_dp #  name as in MySQL service
      - WORDPRESS_DB_USER=wp_user #  user as in MySQL service
      - WORDPRESS_DB_PASSWORD=1234 # password as in MySQL service
    volumes:
      - ./wordpress:/var/www/html

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=1234 #MySQL root password as in MySQL service
